2 VALUES RS_ADDR $ff00 PS_ADDR $fffa
RS_ADDR $90 - VALUE SYSVARS
SYSVARS $80 + VALUE DRV_ADDR
DRV_ADDR 2 + VALUE GRID_MEM
8086A XCOMPL 8086M XCOMPH 8086C COREL
420 424 LOADR ( drivers )
X' FD@ ALIAS (blk@)
X' FD! ALIAS (blk!)
BLKSUB GRIDSUB
: INIT BLK$ FD$ ;
XWRAP INIT
