defc video_scroll_x = $B0
defc video_scroll_y = $B1
defc video_settings = $B2

defc video_address_l = $B3
defc video_address_h = $B4

defc video_table_name = $B8
defc video_table_attribute = $B9
defc video_table_pattern = $BA
defc video_table_palette = $BB

defc video_table_name_increment = $BC
defc video_table_attribute_increment = $BD
defc video_table_pattern_increment = $BE
defc video_table_palette_increment = $BF
