( This is xcomp code that is common to both serial and grid
  binaries. )
0xff00 CONSTANT RS_ADDR
0xfffa CONSTANT PS_ADDR
RS_ADDR 0xb0 - CONSTANT SYSVARS
SYSVARS 0xa0 + CONSTANT GRID_MEM
0 CONSTANT HERESTART
2 LOAD ( assembler common words )
CREATE nativeidx 0 ,
: NATIVE nativeidx @ DUP C, 1+ nativeidx ! ;
200 205 LOADR ( xcomp low )

HERE ORG !
0x11 ALLOT0
( END OF STABLE ABI )
( 11 SUFLW ) 12 C, ," PS underflow"
( 1e SOFLW ) 8 C, ," overflow"
HERE 4 + XCURRENT ! ( make next CODE have 0 prev field )
CODE EXIT NATIVE
CODE (br) NATIVE
CODE (?br) NATIVE
CODE (loop) NATIVE
CODE (b) NATIVE
CODE (n) NATIVE
CODE (s) NATIVE
CODE >R NATIVE
CODE R> NATIVE
CODE 2>R NATIVE
CODE 2R> NATIVE
CODE EXECUTE NATIVE
CODE ROT NATIVE
CODE DUP NATIVE
CODE ?DUP NATIVE
CODE DROP NATIVE
CODE SWAP NATIVE
CODE OVER NATIVE
CODE AND NATIVE
CODE OR NATIVE
CODE XOR NATIVE
CODE NOT NATIVE
CODE + NATIVE
CODE - NATIVE
CODE * NATIVE
CODE /MOD NATIVE
CODE ! NATIVE
CODE @ NATIVE
CODE C! NATIVE
CODE C@ NATIVE
CODE PC! NATIVE
CODE PC@ NATIVE
CODE I NATIVE
CODE I' NATIVE
CODE J NATIVE
CODE BYE NATIVE
CODE ABORT NATIVE
CODE QUIT NATIVE
CODE []= NATIVE
CODE = NATIVE
CODE < NATIVE
CODE FIND NATIVE
CODE 1+ NATIVE
CODE 1- NATIVE
CODE RSHIFT NATIVE
CODE LSHIFT NATIVE
CODE TICKS NATIVE
CODE ROT> NATIVE
CODE |L NATIVE
CODE |M NATIVE
CODE CRC16 NATIVE
CODE CARRY? NATIVE
210 231 LOADR ( forth low )
: (key?) 0 PC@ 1 ;
: EFS@
    1 3 PC! ( read )
    |M 3 PC! 3 PC! ( blkid )
    BLK( |M 3 PC! 3 PC! ( dest )
;
: EFS!
    2 3 PC! ( write )
    |M 3 PC! 3 PC! ( blkid )
    BLK( |M 3 PC! 3 PC! ( dest )
;
( fork between grid and serial begins here )
